import pandas as pd

actual_json_data = {
    "header": {
        "type": "ET_DYN",
        "machine": "EM_X86_64",
        "version": "EV_CURRENT",
        "entry": 1664,
        "phoff": 64,
        "shoff": 6928,
        "flags": 0,
        "ehsize": 64,
        "phentsize": 56,
        "phnum": 9,
        "shentsize": 64,
        "shnum": 29,
        "shstrndx": 28
    },
    "sections": [
        {
            "name": "",
            "type": "SHT_NULL",
            "flags": 0,
            "addr": 0,
            "offset": 0,
            "size": 0,
            "link": 0,
            "info": 0,
            "align": 0,
            "entsize": 0
        },
        {
            "name": ".interp",
            "type": "SHT_PROGBITS",
            "flags": 2,
            "addr": 568,
            "offset": 568,
            "size": 28,
            "link": 0,
            "info": 0,
            "align": 1,
            "entsize": 0
        },
        {
            "name": ".note.ABI-tag",
            "type": "SHT_NOTE",
            "flags": 2,
            "addr": 596,
            "offset": 596,
            "size": 32,
            "link": 0,
            "info": 0,
            "align": 4,
            "entsize": 0
        },
        {
            "name": ".note.gnu.build-id",
            "type": "SHT_NOTE",
            "flags": 2,
            "addr": 628,
            "offset": 628,
            "size": 36,
            "link": 0,
            "info": 0,
            "align": 4,
            "entsize": 0
        },
        {
            "name": ".gnu.hash",
            "type": "SHT_GNU_HASH",
            "flags": 2,
            "addr": 664,
            "offset": 664,
            "size": 28,
            "link": 5,
            "info": 0,
            "align": 8,
            "entsize": 0
        },
        {
            "name": ".dynsym",
            "type": "SHT_DYNSYM",
            "flags": 2,
            "addr": 696,
            "offset": 696,
            "size": 264,
            "link": 6,
            "info": 1,
            "align": 8,
            "entsize": 24
        },
        {
            "name": ".dynstr",
            "type": "SHT_STRTAB",
            "flags": 2,
            "addr": 960,
            "offset": 960,
            "size": 176,
            "link": 0,
            "info": 0,
            "align": 1,
            "entsize": 0
        },
        {
            "name": ".gnu.version",
            "type": "SHT_GNU_versym",
            "flags": 2,
            "addr": 1136,
            "offset": 1136,
            "size": 22,
            "link": 5,
            "info": 0,
            "align": 2,
            "entsize": 2
        },
        {
            "name": ".gnu.version_r",
            "type": "SHT_GNU_verneed",
            "flags": 2,
            "addr": 1160,
            "offset": 1160,
            "size": 48,
            "link": 6,
            "info": 1,
            "align": 8,
            "entsize": 0
        },
        {
            "name": ".rela.dyn",
            "type": "SHT_RELA",
            "flags": 2,
            "addr": 1208,
            "offset": 1208,
            "size": 192,
            "link": 5,
            "info": 0,
            "align": 8,
            "entsize": 24
        },
        {
            "name": ".rela.plt",
            "type": "SHT_RELA",
            "flags": 66,
            "addr": 1400,
            "offset": 1400,
            "size": 120,
            "link": 5,
            "info": 22,
            "align": 8,
            "entsize": 24
        },
        {
            "name": ".init",
            "type": "SHT_PROGBITS",
            "flags": 6,
            "addr": 1520,
            "offset": 1520,
            "size": 23,
            "link": 0,
            "info": 0,
            "align": 4,
            "entsize": 0
        },
        {
            "name": ".plt",
            "type": "SHT_PROGBITS",
            "flags": 6,
            "addr": 1552,
            "offset": 1552,
            "size": 96,
            "link": 0,
            "info": 0,
            "align": 16,
            "entsize": 16
        },
        {
            "name": ".plt.got",
            "type": "SHT_PROGBITS",
            "flags": 6,
            "addr": 1648,
            "offset": 1648,
            "size": 8,
            "link": 0,
            "info": 0,
            "align": 8,
            "entsize": 8
        },
        {
            "name": ".text",
            "type": "SHT_PROGBITS",
            "flags": 6,
            "addr": 1664,
            "offset": 1664,
            "size": 594,
            "link": 0,
            "info": 0,
            "align": 16,
            "entsize": 0
        },
        {
            "name": ".fini",
            "type": "SHT_PROGBITS",
            "flags": 6,
            "addr": 2260,
            "offset": 2260,
            "size": 9,
            "link": 0,
            "info": 0,
            "align": 4,
            "entsize": 0
        },
        {
            "name": ".rodata",
            "type": "SHT_PROGBITS",
            "flags": 2,
            "addr": 2272,
            "offset": 2272,
            "size": 39,
            "link": 0,
            "info": 0,
            "align": 4,
            "entsize": 0
        },
        {
            "name": ".eh_frame_hdr",
            "type": "SHT_PROGBITS",
            "flags": 2,
            "addr": 2312,
            "offset": 2312,
            "size": 68,
            "link": 0,
            "info": 0,
            "align": 4,
            "entsize": 0
        },
        {
            "name": ".eh_frame",
            "type": "SHT_PROGBITS",
            "flags": 2,
            "addr": 2384,
            "offset": 2384,
            "size": 296,
            "link": 0,
            "info": 0,
            "align": 8,
            "entsize": 0
        },
        {
            "name": ".init_array",
            "type": "SHT_INIT_ARRAY",
            "flags": 3,
            "addr": 2100632,
            "offset": 3480,
            "size": 8,
            "link": 0,
            "info": 0,
            "align": 8,
            "entsize": 8
        },
        {
            "name": ".fini_array",
            "type": "SHT_FINI_ARRAY",
            "flags": 3,
            "addr": 2100640,
            "offset": 3488,
            "size": 8,
            "link": 0,
            "info": 0,
            "align": 8,
            "entsize": 8
        },
        {
            "name": ".dynamic",
            "type": "SHT_DYNAMIC",
            "flags": 3,
            "addr": 2100648,
            "offset": 3496,
            "size": 496,
            "link": 6,
            "info": 0,
            "align": 8,
            "entsize": 16
        },
        {
            "name": ".got",
            "type": "SHT_PROGBITS",
            "flags": 3,
            "addr": 2101144,
            "offset": 3992,
            "size": 104,
            "link": 0,
            "info": 0,
            "align": 8,
            "entsize": 8
        },
        {
            "name": ".data",
            "type": "SHT_PROGBITS",
            "flags": 3,
            "addr": 2101248,
            "offset": 4096,
            "size": 196,
            "link": 0,
            "info": 0,
            "align": 32,
            "entsize": 0
        },
        {
            "name": ".bss",
            "type": "SHT_NOBITS",
            "flags": 3,
            "addr": 2101444,
            "offset": 4292,
            "size": 4,
            "link": 0,
            "info": 0,
            "align": 1,
            "entsize": 0
        },
        {
            "name": ".comment",
            "type": "SHT_PROGBITS",
            "flags": 48,
            "addr": 0,
            "offset": 4292,
            "size": 41,
            "link": 0,
            "info": 0,
            "align": 1,
            "entsize": 1
        },
        {
            "name": ".symtab",
            "type": "SHT_SYMTAB",
            "flags": 0,
            "addr": 0,
            "offset": 4336,
            "size": 1680,
            "link": 27,
            "info": 43,
            "align": 8,
            "entsize": 24
        },
        {
            "name": ".strtab",
            "type": "SHT_STRTAB",
            "flags": 0,
            "addr": 0,
            "offset": 6016,
            "size": 655,
            "link": 0,
            "info": 0,
            "align": 1,
            "entsize": 0
        },
        {
            "name": ".shstrtab",
            "type": "SHT_STRTAB",
            "flags": 0,
            "addr": 0,
            "offset": 6671,
            "size": 254,
            "link": 0,
            "info": 0,
            "align": 1,
            "entsize": 0
        }
    ]
}
normalized = pd.json_normalize(actual_json_data)
print(normalized)
# sourceFile = open('demo.txt', 'w')
# print(normalized, file=sourceFile)
# sourceFile.close()
